### ISSUE TITLE
스프린트 2차 API 명세서를 작성한다.

### ISSUE THREAD

**Issue by kong-hana01** [woowacourse-teams/2023-diggin-room#12]
## 핵심 기능
![Image](https://github.com/woowacourse-teams/2023-diggin-room/assets/79015120/79e90e2c-b406-4bf9-8e41-12d6858a6dc9)

**Comment by 0chil** [comment]
2023/7/11 17:34 '다음 룸 조회' 기능에 대해 논의하다 마쳤음.
내일 나머지 기능에 대한 API 명세 및 논의를 마치기로 하였음.

**Comment by 0chil** [comment]
관련 논의를 마쳤음
