### ISSUE TITLE
스크랩된 룸들을 재생 중일 때 목록의 끝에 도달한 경우 새로운 요청을 보내지 않는다.

### ISSUE THREAD

**Issue by boogi-woogi** [woowacourse-teams/2023-diggin-room#147]
### 기능 설명

스크랩 룸 목록의 끝에 도달한 경우 새로운 요청을 보내지 않는 기능을 구현한다

**Comment by DYGames** [comment]
RoomPager의 loadNextRoom 람다에 빈 함수를 넘겨주는 것으로 해결
