### ISSUE TITLE
회원 가입 기능을 구현한다.

### ISSUE THREAD

**Issue by boogi-woogi** [woowacourse-teams/2023-diggin-room#15]
### 기능 설명

id, pw 입력을 이용한 회원가입

### 개발 일정

4시간 - 7.13(목)까지 완료 예정

### 자식 이슈

- #23 
MVVM을 활용해 구현한다는 것이 어려웠다.
아직까지 Coroutine을 사용해 데이터 레이어를 구축하는 것 역시 익숙하지 않아서 추가적인 시간이 필요하다.
- #38 

### 부가 설명

단순히 View에서 수행해야하는 기능들에 대한 구현은 완료

**Comment by DYGames** [comment]
개발 일정 시간도 좋지만 날짜도 적어주세요
