### ISSUE TITLE
커밋 네이밍 컨벤션을 정한다

### ISSUE THREAD

**Issue by DYGames** [woowacourse-teams/2023-diggin-room#3]

**Comment by Songusika** [comment]
** 허용되는 타입**
feat (기능 개발) 
fix (버그 픽스)
docs (문서 작성)
style (코드 리포맷팅, 세미콜론 누락 등)
refactor (리팩터링)
test (테스트 코드 추가)
chore (build.gradle 등 설정파일)

예시)
feat: 유저 엔티티 기능 개발
