### ISSUE TITLE
브랜치 네이밍 컨벤션을 정한다

### ISSUE THREAD

**Issue by boogi-woogi** [woowacourse-teams/2023-diggin-room#5]

**Comment by Songusika** [comment]
**브랜치 네이밍 컨벤션안**
---
1. 이슈 번호로 작성 - 예시) `feature/3` 
2. ~~개발 분야와 이슈 번호로 작성 - 예시) `feature/android/3` or `android-feature/3` ~~
3. ~~구현 기능 이름 작성 - 예시) `feature/android/login` or `android-feature/login`~~

**결론**
이슈 번호로 작성 - 예시) `feature/3`
